server:
  enabled: true
  updateStrategyType: "RollingUpdate"
  dataStorage:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
    storageClass: null
  replicas: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - openbao
              - key: component
                operator: In
                values:
                  - server
          topologyKey: "kubernetes.io/hostname"
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable     = 1
          address         = "0.0.0.0:8200"
        }
        storage "raft" {
          path = "/openbao/data"
          retry_join {
            leader_api_addr = "http://openbao-bundle-0.openbao-bundle-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://openbao-bundle-1.openbao-bundle-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://openbao-bundle-2.openbao-bundle-internal:8200"
          }
        }
injector:
  enabled: false
